"""Aggregate the license texts of installed Python dependencies into one file.

Reads the license metadata already present in the local ``.venv`` (each package ships its own license
under its ``*.dist-info/`` directory) and writes ``THIRD-PARTY-LICENSES-FULL.txt`` at the repo root. Run
from an installed worker with ``uv run python packaging/collect-licenses.py``. Stdlib-only so it works in
the bundled, minimal bootstrap environment as well as the project venv.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_OUTPUT = _REPO_ROOT / "THIRD-PARTY-LICENSES-FULL.txt"


def _site_packages_dirs() -> list[Path]:
    """Return candidate site-packages directories inside the project ``.venv``."""
    venv = _REPO_ROOT / ".venv"
    candidates = [venv / "Lib" / "site-packages", *(venv / "lib").glob("python*/site-packages")]
    return [path for path in candidates if path.is_dir()]


def _read_metadata_field(dist_info: Path, field: str) -> str | None:
    """Return a single header value (e.g. ``Name``/``Version``) from a dist-info METADATA file."""
    metadata = dist_info / "METADATA"
    if not metadata.is_file():
        return None
    prefix = f"{field}:"
    for line in metadata.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip()
        if not line.strip():
            break  # headers end at the first blank line; the body follows
    return None


def _license_files(dist_info: Path) -> list[Path]:
    """Return the bundled license text files for a distribution, if any."""
    found: list[Path] = []
    for base in (dist_info / "licenses", dist_info):
        if base.is_dir():
            found.extend(sorted(p for p in base.glob("*") if p.is_file() and "LICEN" in p.name.upper()))
    return found


def main() -> int:
    """Write the aggregated license file; return a process exit code."""
    site_packages = _site_packages_dirs()
    if not site_packages:
        print("No .venv site-packages found; install the worker first (run it once).", file=sys.stderr)
        return 1

    sections: list[str] = []
    seen: set[str] = set()
    for site in site_packages:
        for dist_info in sorted(site.glob("*.dist-info")):
            name = _read_metadata_field(dist_info, "Name") or dist_info.stem
            if name in seen:
                continue
            seen.add(name)
            version = _read_metadata_field(dist_info, "Version") or "?"
            declared = _read_metadata_field(dist_info, "License-Expression") or _read_metadata_field(
                dist_info,
                "License",
            )
            header = f"{'=' * 78}\n{name} {version}" + (f"  ({declared})" if declared else "")
            bodies = [path.read_text(encoding="utf-8", errors="replace").strip() for path in _license_files(dist_info)]
            body = "\n\n".join(bodies) if bodies else "(no bundled license text; see the package's project page)"
            sections.append(f"{header}\n{'=' * 78}\n\n{body}\n")

    _OUTPUT.write_text(
        "Aggregated license texts for the installed Python dependencies.\n"
        "Generated by packaging/collect-licenses.py from the local .venv.\n\n" + "\n".join(sections),
        encoding="utf-8",
    )
    print(f"Wrote {len(seen)} package license sections to {_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
